export const bookNames = {
    "Gen": { norskBibel: "Gen", bookNameShort: "1Mos", bookName: "Første Mosebok"},
    "Ex": { norskBibel: "Exod", bookNameShort: "2Mos", bookName: "Andre Mosebok"},
    "1Kgs": { norskBibel: "1Kgs", bookNameShort: "1Kong", bookName: "1. Kongebok"},
    "2Kgs": { norskBibel: "2Kgs", bookNameShort: "2Kong", bookName: "2. Kongebok"},
    "Prov": { norskBibel: "Prov", bookNameShort: "Ord", bookName: "Salomos ordspråk"},
    "Job": { norskBibel: "Job", bookNameShort: "Job", bookName: "Jobs bok"},
    "Is": { norskBibel: "Isa", bookNameShort: "Jes", bookName: "Profeten Jesaja"},
    "Joel": { norskBibel: "Joel", bookNameShort: "Joel", bookName: "Profeten Joel"},
    "Zech": { norskBibel: "Zech", bookNameShort: "Sak", bookName: "Profeten Sakarias"},
    "Ezek": { norskBibel: "Ezek", bookNameShort: "Esek", bookName: "Profeten Esekiel"},
    "Jer": { norskBibel: "Jer", bookNameShort: "Jer", bookName: "Profeten Jeremia"},
    "Dan": { norskBibel: "Dan", bookNameShort: "Dan", bookName: "Profeten Daniel"},
    "Mt": { norskBibel: "Matt", bookNameShort: "Matt", bookName: "Matteus' evangelium" },
    "Mk": { norskBibel: "Mark", bookNameShort: "Mark", bookName: "Markus' evangelium" },
    "Lk": { norskBibel: "Luke", bookNameShort: "Luk", bookName: "Lukas' evangelium" },
    "Jn": { norskBibel: "John", bookNameShort: "Joh", bookName: "Johannes' evangelium" },
    "Acts": { norskBibel: "Acts", bookNameShort: "Apg", bookName: "Apostlenes gjerninger" },
    "Rom": { norskBibel: "Rom", bookNameShort: "Rom", bookName: "Paulus' brev til romerne" },
    "1Co": { norskBibel: "1Cor", bookNameShort: "1Kor", bookName: "Paulus' første brev til korinterne" },
    "2Co": { norskBibel: "2Cor", bookNameShort: "2Kor", bookName: "Paulus' andre brev til korinterne" },
    "Gal": { norskBibel: "Gal", bookNameShort: "Gal", bookName: "Paulus' brev til galaterne" },
    "Eph": { norskBibel: "Eph", bookNameShort: "Ef", bookName: "Paulus' brev til efeserne" },
    "Php": { norskBibel: "Phil", bookNameShort: "Fil", bookName: "Paulus' brev til filipperne" },
    "Col": { norskBibel: "Col", bookNameShort: "Kol", bookName: "Paulus' brev til kolosserne" },
    "1Th": { norskBibel: "1Thess", bookNameShort: "1Tess", bookName: "Paulus' første brev til tessalonikerne" },
    "2Th": { norskBibel: "2Thess", bookNameShort: "2Tess", bookName: "Paulus' andre brev til tessalonikerne" },
    "1Ti": { norskBibel: "1Tim", bookNameShort: "1Tim", bookName: "Paulus' første brev til Timoteus" },
    "2Ti": { norskBibel: "2Tim", bookNameShort: "2Tim", bookName: "Paulus' andre brev til Timoteus" },
    "Tts": { norskBibel: "Titus", bookNameShort: "Tit", bookName: "Paulus' brev til Titus" },
    "Phm": { norskBibel: "Phlm", bookNameShort: "Filem", bookName: "Paulus' brev til Filemon" },
    "Heb": { norskBibel: "Heb", bookNameShort: "Heb", bookName: "Brevet til hebreerne" },
    "Jam": { norskBibel: "Jas", bookNameShort: "Jak", bookName: "Jakobs brev" },
    "1Pt": { norskBibel: "1Pet", bookNameShort: "1Pet", bookName: "Peters første brev" },
    "2Pt": { norskBibel: "2Pet", bookNameShort: "2Pet", bookName: "Peters andre brev" },
    "1Jn": { norskBibel: "1John", bookNameShort: "1Joh", bookName: "Johannes' første brev" },
    "2Jn": { norskBibel: "2John", bookNameShort: "2Joh", bookName: "Johannes' andre brev" },
    "3Jn": { norskBibel: "3John", bookNameShort: "3Joh", bookName: "Johannes' tredje brev" },
    "Jude": { norskBibel: "Jude", bookNameShort: "Jud", bookName: "Judas' brev" },
    "Rev": { norskBibel: "Rev", bookNameShort: "Åp", bookName: "Johannes' åpenbaring" }
} as const